export const foodCategories = [
  { id: 1, name: "All", icon: "🍽️" },
  { id: 2, name: "Appetizers", icon: "🥗" },
  { id: 3, name: "Main Course", icon: "🍛" },
  { id: 4, name: "Desserts", icon: "🍰" },
  { id: 5, name: "Beverages", icon: "🥤" },
];

export const menuItems = [
  // Appetizers
  {
    id: 1,
    name: "Spring Rolls",
    category: "Appetizers",
    price: 120,
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400",
    description: "Crispy vegetable spring rolls",
    available: true,
  },
  {
    id: 2,
    name: "Chicken Wings",
    category: "Appetizers",
    price: 180,
    image: "https://images.unsplash.com/photo-1608039755401-742074f0548d?w=400",
    description: "Spicy buffalo wings",
    available: true,
  },
  {
    id: 3,
    name: "Caesar Salad",
    category: "Appetizers",
    price: 150,
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400",
    description: "Fresh romaine with caesar dressing",
    available: true,
  },
  {
    id: 4,
    name: "Garlic Bread",
    category: "Appetizers",
    price: 90,
    image: "https://images.unsplash.com/photo-1573140401552-3fab0b24306f?w=400",
    description: "Toasted bread with garlic butter",
    available: true,
  },

  // Main Course
  {
    id: 5,
    name: "Chicken Biryani",
    category: "Main Course",
    price: 280,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400",
    description: "Aromatic basmati rice with chicken",
    available: true,
  },
  {
    id: 6,
    name: "Paneer Tikka Masala",
    category: "Main Course",
    price: 240,
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400",
    description: "Cottage cheese in creamy tomato gravy",
    available: true,
  },
  {
    id: 7,
    name: "Grilled Salmon",
    category: "Main Course",
    price: 450,
    image: "https://images.unsplash.com/photo-1485921325833-c519f76c4927?w=400",
    description: "Fresh salmon with herbs",
    available: true,
  },
  {
    id: 8,
    name: "Pasta Alfredo",
    category: "Main Course",
    price: 220,
    image: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=400",
    description: "Creamy white sauce pasta",
    available: true,
  },
  {
    id: 9,
    name: "Margherita Pizza",
    category: "Main Course",
    price: 320,
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400",
    description: "Classic pizza with mozzarella",
    available: true,
  },
  {
    id: 10,
    name: "Butter Chicken",
    category: "Main Course",
    price: 300,
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400",
    description: "Creamy tomato chicken curry",
    available: true,
  },

  // Desserts
  {
    id: 11,
    name: "Chocolate Cake",
    category: "Desserts",
    price: 140,
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400",
    description: "Rich chocolate layer cake",
    available: true,
  },
  {
    id: 12,
    name: "Ice Cream Sundae",
    category: "Desserts",
    price: 120,
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400",
    description: "Vanilla ice cream with toppings",
    available: true,
  },
  {
    id: 13,
    name: "Gulab Jamun",
    category: "Desserts",
    image: "src/assets/images/gulab-jamun.webp",
    price: 80,
    description: "Traditional Indian sweet",
    available: true,
  },
  {
    id: 14,
    name: "Tiramisu",
    category: "Desserts",
    price: 160,
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400",
    description: "Italian coffee-flavored dessert",
    available: true,
  },

  // Beverages
  {
    id: 15,
    name: "Mango Lassi",
    category: "Beverages",
    price: 80,
    image: "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=400",
    description: "Traditional yogurt drink",
    available: true,
  },
  {
    id: 16,
    name: "Fresh Lime Soda",
    category: "Beverages",
    price: 60,
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=400",
    description: "Refreshing lime drink",
    available: true,
  },
  {
    id: 17,
    name: "Cappuccino",
    category: "Beverages",
    price: 100,
    image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400",
    description: "Espresso with steamed milk",
    available: true,
  },
  {
    id: 18,
    name: "Masala Chai",
    category: "Beverages",
    price: 50,
    image: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400",
    description: "Spiced Indian tea",
    available: true,
  },
];

export const tables = [
  { id: 1, number: 1, status: "available", capacity: 4, currentOrders: [] },
  { id: 2, number: 2, status: "occupied", capacity: 2, currentOrders: [1, 2] },
  { id: 3, number: 3, status: "available", capacity: 6, currentOrders: [] },
  { id: 4, number: 4, status: "occupied", capacity: 4, currentOrders: [3] },
  { id: 5, number: 5, status: "available", capacity: 2, currentOrders: [] },
  { id: 6, number: 6, status: "reserved", capacity: 8, currentOrders: [] },
  { id: 7, number: 7, status: "available", capacity: 4, currentOrders: [] },
  { id: 8, number: 8, status: "occupied", capacity: 4, currentOrders: [4, 5] },
  { id: 9, number: 9, status: "available", capacity: 2, currentOrders: [] },
  { id: 10, number: 10, status: "available", capacity: 6, currentOrders: [] },
];
